### ISSUE TITLE
Add UTM codes to settings page links

### ISSUE THREAD

**Issue by Barn2** [Barn2Media/posts-data-table#7]
**1. Settings page links**

I've just noticed that there are no UTM codes in the links to the Pro version which appear inline on the settings. There are already UTM's in the sidebar banner on the settings page, but not on the inline links. Please could you add these in the next update (not urgent). 

The UTM code for these links should be /?utm_source=settings&utm_medium=settings&utm_campaign=settingsinline&utm_content=ptss-ptp. 

**2. Missing UTM's on wordpress.org page**

There are loads of links to barn2.com on https://wordpress.org/plugins/posts-data-table which are missing UTM's, please could you add these. The UTM should be /?utm=content&utm_source=wporg&utm_content=posts-table-free.

**Comment by LuigiPulcini** [comment]
I have just pushed the new version 1.3.8 that adds the recommended UTM codes to every link pointing to the barn2.com domain on both the Settings page and the `readme.txt`.

In regards to the `readme.txt` file, the UTM codes were already part of all the links pointing to the Posts Table Pro sales page only (i.e. `https://barn2.com/wordpress-plugins/posts-table-pro`), but not on any other barn2 URLs.

**Comment by Barn2** [comment]
Brilliant, thanks. Have you added the UTM to the other Barn2 UTR's in the
readme now?

**Comment by LuigiPulcini** [comment]
Yes, I have. And the new readme is already available when you visit the [plugin page](https://wordpress.org/plugins/posts-data-table/).

**Comment by andykeith** [comment]
Thanks for fixing the UTM tags on the settings page. I noticed there are still some links on the [wordpress.org page](https://wordpress.org/plugins/posts-data-table/) missing the UTM tags. I must have missed these when those links were added to the readme file:

- "member directory" and "audio gallery" in the first section.
- "create a WordPress file manager" under HOW TO CREATE YOUR OWN WORDPRESS POST TABLES.

**Comment by LuigiPulcini** [comment]
Sorry for missing those three links, Andy. Would updating just the `readme.txt` file as per our Wiki instructions apply to this case as well? The Wiki only refers to changes to the `Tested up to` version but I assume it would work with the rest of the `readme.txt` file as well.

Let me know and I will push a new commit with those changes.

**Comment by andykeith** [comment]
Hi Luigi, thanks. Yes if you push to master with just changes to the readme.txt file, it will deploy just that file to wordpress.org. You don’t need to do a new tag or anything. 

Best regards,

Andy Keith
Barn2 Plugins

**Comment by LuigiPulcini** [comment]
The action was completed successfully and the WP page already reflects the changes.

**Comment by andykeith** [comment]
Perfect, thanks!
