### ISSUE TITLE
Minor UTM code format change for next version (not urgent)

### ISSUE THREAD

**Issue by Barn2** [Barn2Media/posts-data-table#8]
We are making the format of our UTM codes more consistent over time. In the next version (no need to do a release just for this), please could you change the UTM code on the PTSS wordpress.org page in the readme to: https://barn2.com/wordpress-plugins/posts-table-pro/?utm_source=wporg&utm_medium=freeplugin&utm_campaign=freepluginwporg&utm_content=posts-table-free

This adds the 'campaign' parameter to the UTM code, which is currently missing.

**Comment by amirition** [comment]
Fixed in version 1.3.9
